### ISSUE TITLE
EPIC - KG MVP

### ISSUE THREAD

**Issue by dosumis** [EBISPOT/scxa_kg#2]
- [ ] #1 
- [ ] Extend CxG validator
- [ ] Set up [OBASK](https://github.com/OBASKTools/obask) instance with basic config 
    - load uberon composite metazoan - has all the cell and anatomy ontologies you need, safely merged.
    - Load a slice of EFO with the terms you need - be conservative with the terms you take.
    - Review other ontologies needed.
- [ ] Pandasaurus_cxg - extend to support all metadata loading & support dataset representation and metadata.
